%> @file ccd_photosensor.m
%> @brief This routine performs initial conversion of the light from the irradiance and photons to electrons.
%> @author Mikhail V. Konnik
%> @date   17 January 2011, reworked on 4 December 2014.
%> 
%> @section ccdphotosensor Convesrion from photons to electrons.
%> The process from incident photons to the digital numbers appeared on the image is outlined. See @ref secphoton2electron "this page" about particular implementation.
%>
%======================================================================
%> @param Uin		= light field incident on the photosensor [matrix NxM], [Watt/m2].
%> @param ccd		= structure that contains parameters of the sensor (exposure time and so on).
%>
%> @retval ccd 		= structure with new variable @b Signal_CCD_electrons signal of the photosensor in electrons [matrix NxM], [e].
% ======================================================================
function ccd = ccd_photosensor(Uin,ccd);

ccd = ccd_set_photosensor_constants(ccd,Uin); %%% defining the constants such as speed of light c, Plank's h, and others.


%%%%% <----- ### Start:: adding light noises
if (ccd.flag.darkframe ~= 1) %%%%%%%%#### Section: if this is NOT a complete darkness
    ccd = ccd_photosensor_lightnoises(ccd, Uin); 
end 
%%%%% <----- ### END:: adding light noises


%%%%% <----- ### Start:: adding dark current noise
if (ccd.flag.darkcurrent == 1)
     ccd = ccd_photosensor_darknoises(ccd);
end
%%%%% <----- ### END:: adding dark current noise


%%%%% <----- ### Start:: adding dark current and light electrons 
ccd.Signal_CCD_electrons = ccd.light_signal + ccd.dark_signal; %%% adding the electrones generated by dark signal and electrones generated by light.

% figure, imagesc(ccd.light_signal);
% figure, imagesc(ccd.dark_signal);

    %%%%%%%%%%%######### Full-well checkup (if there more electrons than depth of the pixel - saturate the pixel)
        idx = (ccd.Signal_CCD_electrons>=ccd.FW_e); %%% find all of pixels that are saturated (there are more electrons that full-well of the pixel)
        ccd.Signal_CCD_electrons(idx) = ccd.FW_e;  %% saturate the pixel if there are more electrons than full-well.

        idx = (ccd.Signal_CCD_electrons<0); %%% find all of pixels that are less than zero
        ccd.Signal_CCD_electrons(idx) = 0; %%% truncate pixels that are less than zero to zero. (there no negative electrons).
    %%%%%%%%%%%######### END Full-well checkup

ccd.Signal_CCD_electrons = floor(ccd.Signal_CCD_electrons);  %% round the number of electrons.        
%%%%% <----- ### END:: adding dark current and light electrons     


%%%%% <----- ### Start:: Sense Node - charge-to-voltage conversion
ccd = ccd_sense_node_chargetovoltage(ccd); %%% Charge-to-Voltage conversion by Sense Node
%%%%% <----- ### END:: Sense Node - charge-to-voltage conversion


%%%%% <----- ### Start:: Source Follower - Voltages
ccd = ccd_source_follower(ccd); %%% Signal's Voltage amplification by Source Follower
%%%%% <----- ### END:: Source Follower - Voltages


%%%%% <----- ### Start:: Correlated Double Sampling
ccd = ccd_cds(ccd); %%% Signal's amplification and denoising by Correlated Double Sampling
%%%%% <----- ### END:: Correlated Double Sampling


%%%%% <----- ### Start:: Analogue-To-Digital Converter
ccd = ccd_adc(ccd); %% Quantizator ADC
%%%%% <----- ### END:: Analogue-To-Digital Converter